version: '3.8'

services:
  app:
    stdin_open: true
    tty: true
    environment:
      - TURBO_TELEMETRY_DISABLED=1
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - web_node_modules:/app/apps/web/node_modules
      - docs_node_modules:/app/apps/docs/node_modules
      - ui_node_modules:/app/packages/ui/node_modules
      - db_node_modules:/app/packages/db/node_modules

  postgres:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

volumes:
  node_modules:
  web_node_modules:
  docs_node_modules:
  ui_node_modules:
  db_node_modules: