version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile.dev
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    volumes:
      - ..:/app:cached
    environment:
      - NODE_ENV=development
    command: sleep infinity